package org.castello.game;

public enum Action {
    // HUNTERS
    EAU_BENITE,
    FUMIGATION_AIL,
    PISTEUR,
    FEU_DE_CAMP,
    NET,
    PIT,
    PROVOCATION,
    INCENDIAIRE,
    AMBUSH,
    LONELY,
    BLESSED_STAKE,
    SACRED_ROSARY,
    CHARISMATIQUE,
    MARCHAND_ITINERANT,
    CAISSE_ABANDONNEE,
    // VAMPIRE
    CATACLYSME,
    CLONES_OMBRE,
    IMAGE_MIROIR,
    PRESENCE_ECRASANTE,
    ECLIPSE,
    BLOOD_MOON,
    VOILE_DE_BRUME,
    FAIM_IRREPRESSIBLE,
    MARQUE_TENEBREUSE,
    AFFAIBLISSEMENT_OCCULTE,
    PASSAGE_SECRET,
    AVIDITE_NOCTURNE
}