# Fichier chargé quand SPRING_PROFILES_ACTIVE=preprod
server:
  # Derrière Nginx Proxy Manager: fais confiance aux en-têtes X-Forwarded-*
  forward-headers-strategy: native

danger:
  wipe:
    enabled: false

app:
  cors:
    # Origines autorisées pour les requêtes navigateur
    allowed-origins:
      - https://red-dawn-raid-preprod.castello.ovh

spring:
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    root: info
    org.castello: debug
    org.hibernate.SQL: info  # évite le spam SQL en préprod
