spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/red_dawn_raid
    username: rdr_dev
    password: azerty
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.hibernate.SQL: debug
# === Dossier où le backend stockera/servira les fichiers uploadés ===
# - Valeur par défaut: /data/uploads (très pratique pour monter un volume en Docker)
# - En local (hors Docker), override par env: APP_UPLOAD_DIR=/chemin/local
app:
  upload:
    dir: ${APP_UPLOAD_DIR:./uploads}
  cors:
    allowed-origins:
      - http://localhost:4200