server:
  forward-headers-strategy: native

danger:
  wipe:
    enabled: false

app:
  cors:
    allowed-origins:
      - https://red-dawn-raid.castello.ovh

spring:
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    root: info
    org.castello: debug
    org.hibernate.SQL: warn
